### ISSUE TITLE
pod details not clickable when pod shell is opened

### ISSUE THREAD

**Issue by cachila** [alebcay/openlens-node-pod-menu#7]
The issue is that when a pod shell is opened, the pod details are not clickable in the highlighted area. (It seems like the .KubeObjectDetails z-index attribute is missing)

![image](https://user-images.githubusercontent.com/5391176/211788365-a4c01f2a-a692-4e1a-b074-179ece2aab59.png)

**Comment by alebcay** [comment]
Hi, thanks for the bug report. The CSS characteristics of the details pane and terminal area are set in the OpenLens application itself, this extension has no control over that behavior.

I am able to reproduce this behavior in 6.3.0 without this extension installed (just open a regular terminal instead of pod shell, pod details are similarly not clickable).

I am no longer able to reproduce this behavior when building from latest OpenLens `HEAD`, pod details are correctly on top again. So this should be fixed in the next Lens/OpenLens release, whenever that will drop.

**Comment by cachila** [comment]
Thanks for the response

Actually I reported this there but they advised to report it here. https://github.com/MuhammedKalkan/OpenLens/issues/94#issuecomment-1377661493

Hope this get fixed on the next release

**Comment by alebcay** [comment]
For future reference, the correct place to report this is https://github.com/lensapp/lens. 6.4.0-alpha.1 and 6.4.0-alpha.2 were released today and should contain a fix for this.
